sudo: required

language: node

services:
  - docker
  - couchdb

before_install:
  - docker build -t insanity54/loluwin .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push insanity54/loluwin
  - docker run -d -p 3000 insanity54/loluwin
  - docker ps -a

script:
  - docker ps -a | grep loluwin